#include "printBatterySensorValue.h"

void displayBatterySensorValueList(batterySensorValue sensorValue,printSensorDataInterface &printSensorDataObject);
bool sendBatteryParameterValues(printSensorDataInterface &printSensorDataObject);
